/**
 * @author Piyush Chaudhary
 */
package hackerRank;

/**
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 *
 */
public class FindTheDifference {
	public char findTheDifference(String s, String t) { // Linear time and constant space solution.
		int res = 0;
		for (int i = 0; i < s.length(); i++) {
			int chs = s.charAt(i) - 'a';
			res = res ^ chs;
		}
		for (int i = 0; i < t.length(); i++) {
			int cht = t.charAt(i) - 'a';
			res = res ^ cht;
		}

		char ch = (char) (res + 'a');
		return ch;
	}
}
