/**
 * @author Piyush Chaudhary
 */
package hackerRank;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * three million, find the sum of the odd-valued terms.
 *
 */
public class OddFibonacci {
	public static int sumOfOddFibonacci() {
		int threshold = 10;
		int prevNumber = 1;
		int currNumber = 2;
		int result = 1;
		while (currNumber < threshold) {
			if (currNumber % 2 != 0) {
				result += currNumber;
			}
			currNumber += prevNumber;
			prevNumber = currNumber - prevNumber;
		}

		return result;
	}

	
	public static void main(String[] args) {
		System.out.println(sumOfOddFibonacci());
	}
}
